name: Python CI/CD

on:
    push:
        paths-ignore:
            - "**/README.md"
            - "**/CHANGELOG.md"
            - "**/LICENSE"

    workflow_dispatch:

permissions:
    statuses: write
    pull-requests: write

jobs:

    check_branch:
        runs-on: ubuntu-latest
        steps:
          - name: Check branch
            if: github.base_ref == 'main' && github.head_ref != 'develop'
            run: |
              echo "ERROR: You can only merge to main from develop."
              exit 1
    
    build:
        strategy:
            matrix:
                python: ["3.8", "3.9", "3.10", "3.11", "3.12"]

        runs-on: ubuntu-latest

        steps:
            - name: Build Information
              run: echo "Running project CI [Python ${{matrix.python}} on ${{runner.os}}]"

            - name: Set Commit Status to Pending
              uses: ouzi-dev/commit-status-updater@v2

            - name: Checkout Code From "${{github.ref_name}}"
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{matrix.python}}
                  cache: "pip"

            - name: Upgrade Pip
              run: python -m pip install --upgrade pip

            - name: Install Package
              run: pip install -e .[ci]

            - name: Linting
              run: |
                  ruff check --output-format=github src

            - name: Static Type Analysis
              run: |
                  mypy src

            - name: Run Tests
              run: |
                  python -m pytest --junitxml=reports/tests.xml --cov --cov-fail-under=70

            - name: Generate Coverage Report
              run: python -m coverage xml -o reports/coverage.xml

            - name: Publish Test Results
              uses: actions/upload-artifact@v3
              with:
                  name: tests.xml
                  path: reports/tests.xml

            - name: Publish Code Coverage Results
              uses: actions/upload-artifact@v3
              with:
                  name: coverage.xml
                  path: reports/coverage.xml

            - name: Update Commit Status With Build Result
              if: always()
              uses: ouzi-dev/commit-status-updater@v2
              with:
                  status: "${{ job.status }}"

    test-pypi-publish:
        if: github.ref == 'refs/heads/develop'
        name: publish package to PyPI [TEST]
        needs: build
        runs-on: ubuntu-latest
        environment:
            name: test
        permissions:
            id-token: write
        
        steps:
            - name: Build Information
              run: echo "Publishing package"

            - name: Checkout Code From "${{github.ref_name}}"
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12
                  cache: "pip"

            - name: Upgrade Pip
              run: python -m pip install --upgrade pip

            - name: Install Package
              run: pip install -e .[ci]

            - name: Build package
              run: |
                  python -m build

            - name: Publish package distributions to test PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                repository-url: https://test.pypi.org/legacy/
    
    pypi-publish:
        if: github.ref == 'refs/heads/main'
        name: publish package to PyPI [RELEASE]
        needs: build
        runs-on: ubuntu-latest
        environment:
            name: release
        permissions:
            id-token: write
        
        steps:
            - name: Build Information
              run: echo "Publishing package"

            - name: Checkout Code From "${{github.ref_name}}"
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12
                  cache: "pip"

            - name: Upgrade Pip
              run: python -m pip install --upgrade pip

            - name: Install Package
              run: pip install -e .[ci]

            - name: Build package
              run: |
                python -m build

            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
